services:
  - type: web
    name: SafeRoute
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: POSTHOG_API_KEY
        sync: false
      - key: POSTHOG_HOST
        sync: false
